server:
  port: 9053

spring:
  data:
    mongodb:
      uri: mongodb://mongo-server:27017/ProyectoS1Bank
  application:
    name: debit-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
resilience4j:
    circuitbreaker:
        configs:
            default:
                registerHealthIndicator: true
                slidingWindowSize: 10
                minimumNumberOfCalls: 5
                permittedNumberOfCallsInHalfOpenState: 3
                automaticTransitionFromOpenToHalfOpenEnabled: true
                waitDurationInOpenState: 2s
                failureRateThreshold: 50
                eventConsumerBufferSize: 10
                recordExceptions:
                    - org.springframework.web.client.HttpServerErrorException
                    - java.util.concurrent.TimeoutException
                    - java.io.IOException
                    - java.net.ConnectException
        instances:
            customerServiceCircuitBreaker:
                baseConfig: default

