server:
  port: 9053

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27018/ProyectoS1Bank
  application:
    name: debit-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
