server:
  port: 9053

spring:
  data:
    mongodb:
      uri: mongodb+srv://dbUser:j6FPw3opZsiHuiWT@db-everis-bank.pmiyr.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
  application:
    name: debit-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-bc.azurewebsites.net/eureka/
