spring:
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer/**
            - Path=/customertype/**
          filters:
            - StripPrefix=1
        - id: credit-service
          uri: lb://credit-service
          predicates:
            - Path=/api/credit/**
          filters:
            - StripPrefix=2
        - id: creditcard-service
          uri: lb://creditcard-service
          predicates:
            - Path=/api/creditcard/**
          filters:
            - StripPrefix=2
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payment/**
          filters:
            - StripPrefix=2
        - id: paymentCredit-service
          uri: lb://paymentCredit-service
          predicates:
            - Path=/api/paymentcard/**
          filters:
            - StripPrefix=2
        - id: consumption-service
          uri: lb://consumption-service
          predicates:
            - Path=/api/consumption/**
          filters:
            - StripPrefix=2
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/transaction/**
          filters:
            - StripPrefix=2
        - id: savingaccount-service
          uri: lb://savingaccount-service
          predicates:
            - Path=/api/savingAccount/**
          filters:
            - StripPrefix=2
        - id: deposit-service
          uri: lb://deposit-service
          predicates:
            - Path=/api/deposit/**
          filters:
            - StripPrefix=2
        - id: retire-service
          uri: lb://retire-service
          predicates:
            - Path=/api/retire/**
          filters:
            - StripPrefix=2
        - id: currentaccount-service
          uri: lb://currentaccount-service
          predicates:
            - Path=/api/currentAccount/**
          filters:
            - StripPrefix=2
        - id: transfer-service
          uri: lb://transfer-service
          predicates:
            - Path=/api/transfer/**
          filters:
            - StripPrefix=2
        - id: servicio-fixedTermAccound
          uri: lb://servicio-fixedTermAccound
          predicates:
            - Path=/api/fixedTermAccound/**
          filters:
            - StripPrefix=2

