server:
  port: 8092

config:
  base:
    endpoint:
      customer: http://localhost:8090/api/credit

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27018/ProyectoS1Bank
  application:
    name: payment-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

