server:
  port: 8093

config:
  base:
    endpoint:
      customer: http://localhost:8091/api/creditcard

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27018/ProyectoS1Bank
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: paymentCredit-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
