server:
  port: 8085

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27018/ProyectoS1Bank
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: retir-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/